# Google Cloud Build configuration for automated deployment
steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['ci']

  # Build the application
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml', '--quiet']

# Set build timeout
timeout: '1200s'

# Specify machine type for faster builds
options:
  machineType: 'E2_HIGHCPU_8'