steps:
  # Step 1: Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']

  # Step 2: Build the application
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Step 3: Copy files to VM
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute scp --recurse . techpartner-exact:/tmp/techpartner-update --zone=us-central1-a --quiet

  # Step 4: Deploy on VM
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh techpartner-exact --zone=us-central1-a --command="
          sudo cp -r /tmp/techpartner-update/* /opt/techpartner-platform/
          cd /opt/techpartner-platform
          npm install --production
          pm2 restart all
          pm2 status
        " --quiet

timeout: '600s'

# Use secrets from Secret Manager
availableSecrets:
  secretManager:
    - versionName: projects/glossy-agency-448211-s4/secrets/DATABASE_URL/versions/latest
      env: DATABASE_URL
    - versionName: projects/glossy-agency-448211-s4/secrets/JWT_SECRET/versions/latest
      env: JWT_SECRET
    - versionName: projects/glossy-agency-448211-s4/secrets/JWT_REFRESH_SECRET/versions/latest
      env: JWT_REFRESH_SECRET