steps:
  # Build the application
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['ci']
    
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'Dockerfile.production',
      '-t', 'gcr.io/$PROJECT_ID/techpartner-new:latest',
      '.'
    ]
    
  # Push to Container Registry  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/techpartner-new:latest']
    
images:
  - 'gcr.io/$PROJECT_ID/techpartner-new:latest'

timeout: '1200s'