import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>صفحة الدخول</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          مرحبا بكم في موقعنا
        </h1>

        <p className={styles.description}>
          ابدأ بالضغط على الزر أدناه
        </p>

        <div className={styles.grid}>
          <a href="#" className={styles.card}>
            <h2>تعلم &rarr;</h2>
            <p>اكتشف خدماتنا</p>
          </a>

          <a href="#" className={styles.card}>
            <h2>ابدأ الآن &rarr;</h2>
            <p>سجل في خدماتنا</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          تمت إدارة الموقع بواسطة{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
